"""Add previous_workflow_stage and available_windows to event model

Revision ID: 6ba344f582b6
Revises: 789ff4cd19ef
Create Date: 2025-08-06 12:21:14.928285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ba344f582b6'
down_revision = '789ff4cd19ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previous_workflow_stage', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('available_windows', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('available_windows')
        batch_op.drop_column('previous_workflow_stage')

    # ### end Alembic commands ###
