"""Add selected time fields to Event model

Revision ID: 789ff4cd19ef
Revises: 0ec0bfef5098
Create Date: 2025-08-04 22:07:16.987168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '789ff4cd19ef'
down_revision = '0ec0bfef5098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('selected_start_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('selected_end_time', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('selected_end_time')
        batch_op.drop_column('selected_start_time')
        batch_op.drop_column('selected_date')

    # ### end Alembic commands ###
