[variables]
NIXPACKS_PYTHON_VERSION = "3.12"

[phases.setup]
nixPkgs = ["python312", "gcc", "postgresql"]

[phases.install] 
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = ". /opt/venv/bin/activate && gunicorn run:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --log-level info"
